# -*- coding: utf-8 -*-
"""run_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sKOWIgHCHr5iZolK92872Vgzshw1AFQf
"""

# Getting and Cleaning Data Course Project
# Author : Ali Rabiee

# Install required packages
install.packages("data.table", dependencies=TRUE)
install.packages("reshape2", dependencies=TRUE)

# Getting Data from url address
packages <- c("data.table", "reshape2")
sapply(packages, require, character.only=TRUE, quietly=TRUE)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", file.path(getwd(), "my_data.zip"))
unzip(zipfile = "my_data.zip")

# Extracts the measurements on the mean and standard deviation for each measurement
act_labels <- fread(file.path(getwd(), "UCI HAR Dataset/activity_labels.txt"), col.names = c("classLabels", "activityName"))                       
features <- fread(file.path(getwd(), "UCI HAR Dataset/features.txt"), col.names = c("index", "featureNames"))                
mean_std <- grep("(mean|std)\\(\\)", features[, featureNames])
measurements <- features[mean_std, featureNames]
measurements <- gsub('[()]', '', measurements)

# Load train dataset
train <- read.table("UCI HAR Dataset/train/X_train.txt")[mean_std]
train_act <- read.table("UCI HAR Dataset/train/y_train.txt")
train_sub <- read.table("UCI HAR Dataset/train/subject_train.txt")
train <- cbind(train_sub, train_act, train)

# Load test dataset
test <- read.table("UCI HAR Dataset/test/X_test.txt")[mean_std]
test_act <- read.table("UCI HAR Dataset/test/y_test.txt")
test_sub <- read.table("UCI HAR Dataset/test/subject_test.txt")
test <- cbind(test_sub, test_act, test)

# Merges the training and the test sets to create one data set
merged <- rbind(train, test)
colnames(merged) <- c("subNum", "Activity", measurements)

# turn activities & subjects into factors
merged$Activity <- factor(merged$Activity, levels = act_labels[,1], labels = act_labels[,2])
merged$subNum <- as.factor(merged$subNum)
merged.melted <- melt(merged, id = c("subNum", "Activity"))
merged.mean <- dcast(merged.melted, subNum + Activity ~ variable, mean)
write.table(merged.mean, "result.txt", row.names = FALSE, quote = FALSE)read.table("UCI HAR Dataset/train/X_train.txt")[mean_std]
train_act <- read.table("UCI HAR Dataset/train/y_train.txt")
train_sub <- read.table("UCI HAR Dataset/train/subject_train.txt")
train <- cbind(train_sub, train_act, train)

# Load test dataset
test <- read.table("UCI HAR Dataset/test/X_test.txt")[mean_std]
test_act <- read.table("UCI HAR Dataset/test/y_test.txt")
test_sub <- read.table("UCI HAR Dataset/test/subject_test.txt")
test <- cbind(test_sub, test_act, test)

# Merges the training and the test sets to create one data set
merged <- rbind(train, test)
colnames(merged) <- c("subNum", "Activity", measurements)

# turn activities & subjects into factors
merged$Activity <- factor(merged$Activity, levels = act_labels[,1], labels = act_labels[,2])
merged$subNum <